openapi: 3.1.0
info:
  title: RAG Agent API
  description: Backend API for RAG agent that answers questions about Physical AI and Humanoid Robotics book
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Development server
  - url: https://api.example.com/v1
    description: Production server

paths:
  /chat:
    post:
      summary: Send a message to the RAG agent
      description: Receives a user question and returns an answer grounded in book content
      operationId: sendChatMessage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChatRequest'
      responses:
        '200':
          description: Successful response with agent answer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChatResponse'
        '400':
          description: Invalid request parameters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /sessions/{session_id}:
    get:
      summary: Get conversation session
      description: Retrieves the full conversation history for a session
      operationId: getSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Session details and messages
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SessionResponse'
        '404':
          description: Session not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

    delete:
      summary: Delete conversation session
      description: Removes a session and its conversation history
      operationId: deleteSession
      parameters:
        - name: session_id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Session deleted successfully
        '404':
          description: Session not found

  /health:
    get:
      summary: Health check
      description: Returns API health status
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'

components:
  schemas:
    ChatRequest:
      type: object
      required:
        - message
      properties:
        message:
          type: string
          minLength: 1
          maxLength: 10000
          description: User's question or message
        session_id:
          type: string
          format: uuid
          description: Optional session ID for continuing conversation
        max_results:
          type: integer
          minimum: 1
          maximum: 20
          default: 5
          description: Maximum number of chunks to retrieve
        threshold:
          type: number
          minimum: 0.0
          maximum: 1.0
          default: 0.5
          description: Minimum relevance score threshold

    ChatResponse:
      type: object
      required:
        - answer
        - sources
        - session_id
        - latency_ms
      properties:
        answer:
          type: string
          description: Agent's generated response
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
          description: Citations used in the response
        session_id:
          type: string
          format: uuid
          description: Session identifier
        latency_ms:
          type: number
          description: Total response time in milliseconds

    SessionResponse:
      type: object
      required:
        - session_id
        - messages
        - created_at
        - updated_at
      properties:
        session_id:
          type: string
          format: uuid
        messages:
          type: array
          items:
            $ref: '#/components/schemas/Message'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Message:
      type: object
      required:
        - role
        - content
        - timestamp
      properties:
        role:
          type: string
          enum:
            - user
            - assistant
        content:
          type: string
        sources:
          type: array
          items:
            $ref: '#/components/schemas/Source'
        timestamp:
          type: string
          format: date-time

    Source:
      type: object
      required:
        - url
        - heading
        - score
      properties:
        url:
          type: string
          format: uri
          description: Source documentation URL
        heading:
          type: string
          description: Page or section heading
        section_path:
          type: string
          description: Hierarchical path in documentation
        score:
          type: number
          minimum: 0.0
          maximum: 1.0
          description: Relevance score from retrieval
        text:
          type: string
          description: Relevant excerpt from the chunk

    Error:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Error type code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Additional error details

    HealthResponse:
      type: object
      required:
        - status
        - version
      properties:
        status:
          type: string
          enum:
            - healthy
            - degraded
            - unhealthy
        version:
          type: string
        services:
          type: object
          properties:
            qdrant:
              type: string
              enum:
                - connected
                - disconnected
            cohere:
              type: string
              enum:
                - connected
                - disconnected
            openai:
              type: string
              enum:
                - connected
                - disconnected

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
